### ISSUE TITLE
Realign visual branding

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#39]
Move toward a more Sign Languages specific visual branding.

### Colors
- [x] grey `#474847` or `#484848` (or variants) https://github.com/lingua-libre/SignIt/commit/17a39d2b91d873ab9e7fa0acbe89f8056d89a6f9
- [x] green #00a99d https://github.com/lingua-libre/SignIt/commit/a1e40d0c4fc4316eea3f4b5af6d433af17e1ee58#diff-5f677133bd3f5a4dddc8497184199679c2c3b434018feaad5325405970cc3dde
- [x] NOT TO USE. blue #36c

#### Phase 1
- [x] Decide a base color : KEEP GREEN
- [x] Create new logo with hands https://commons.wikimedia.org/wiki/File:Lingualibre_SignIt-logo.svg
- [x] Adapt new logo with right color

#### Phase 2
- [x] Integrate new logo to repository https://github.com/lingua-libre/SignIt/tree/master/icons
- [x] regenerate derivative icons https://github.com/lingua-libre/SignIt/tree/master/icons
- [x] commit to repository
- [x] release on github https://github.com/lingua-libre/SignIt/releases 1.0.19

#### Phase 3
- [ ] recreate documentation screenshots https://github.com/lingua-libre/SignIt/tree/master/doc
- [ ] update commons screenshots https://commons.wikimedia.org/wiki/Category:Lingua_Libre_SignIt
  - [ ] meta https://meta.wikimedia.org/wiki/Lingua_Libre/SignIt
  - [ ] wikidata https://www.wikidata.org/wiki/Q113354157

#### Phase4
- [ ] redeploy on firefox addon store https://addons.mozilla.org/en-US/firefox/addon/lingua-libre-signit/

**Comment by sonalgaud12** [comment]
Hi, is anyone working on this issue? if not can some one assign me this issue?

**Comment by hugolpz** [comment]
Hello @sonalgaud12 , I did Phase 1 and 2. But I'm not available for phase 3 yet. If you want to push forward, you are welcome. I can then redeploy on Firefox add-ons store.
