### ISSUE TITLE
Convert `.ogv` files to more standard format

### ISSUE THREAD

**Issue by hugolpz** [lingua-libre/SignIt#80]
### Bug
Elix videos are not working on Chromium.

### Cause 
| extension | `.ogv` | `.webm` 
| --- | --- | --- | 
| support | poor | widespread |
| source |https://caniuse.com/ogv | https://caniuse.com/webm |

### Todo
- [x] Download Commons category using [wiki-download-many-category_files.js](https://github.com/hugolpz/WikiapiJS-Eggs/blob/main/wiki-download-many-category_files.js)
- [x] Identify proper output format, see https://commons.wikimedia.org/wiki/File:Analogie_Nf_1_2_1_-_Elix.ogv#transcodestatus
- [x] Convert
- [x] List existing : Lingualibre Qid + Commons filenames 
- [ ] <s>Rename existing to .webm</s> : fails due to `Error: File extension does not match MIME type`
- [x] Reupload <s>over</s> aside :
  - `.ogv` : [Category:Files_supported_by_Wikimedia_France_-_Elix_-_obsolete](https://commons.wikimedia.org/wiki/Category:Files_supported_by_Wikimedia_France_-_Elix_-_obsolete)
  - `.webm`: [Category:Files_supported_by_Wikimedia_France_-_Elix](https://commons.wikimedia.org/wiki/Category:Files_supported_by_Wikimedia_France_-_Elix)
- [x] <s>Request copy of structured data to new files</s> Some maintenance bot update it slowly.
- [x] Edit old with {supersed2}
- [x] Update all Lingualibre items' P3 values : solves with the help of https://github.com/kanasimi/wikiapi/issues/71 thank to @Kanasimi 😍 

### Post issue #80
The following tasks are not in SignIt scope, bu rather in Commons maintenance scope.
Their (no) achievement doesn't affect SignIt's #80 issue.
- [ ] Edit old with `#REDIRECT` or delete those pages. See [Commons discussion](https://commons.wikimedia.org/w/index.php?title=Commons:Village_pump&oldid=885255741#Supersede_images_:_what_to_do_with_old_page_?)

**Comment by hugolpz** [comment]
✅ #80 is done ! 
- **On Lingualibre :** I updated Lingualibre.org wikibase data replacing references to all .ogv to the new .webm.  so it nows loads the .webm.
- **On SignIt :** therefore, ALL the videos fetched by SignIt display well in Chrome too ￼﻿﻿￼﻿  .
- **On Commons :** the situation will be a bit messy for few more weeks, with both the .ogv and .webm files on Commons. I grouped and tagged all obsolete files. This should clear up this late June or July, when bots clean things up, replace-migrate usages across wikimedia projects to the new files, to then remove obsolete files.
